FROM {{ backend_base_image }}
WORKDIR /code
COPY backend/requirements.txt /code/requirements.txt
RUN pip install --upgrade -r requirements.txt
COPY backend/ /code/
RUN rm -rf scripts/templates
COPY frontend/ /code/scripts/templates/
CMD ["python", "app.py"]
