FROM {{ frontend_base_image }} AS frontend
WORKDIR /code
COPY frontend/package.json .
RUN npm install
COPY frontend/ .
RUN node "node_modules/@angular/cli/bin/ng" build --configuration production --output-path build


FROM {{ backend_base_image }}
WORKDIR /code
COPY backend/requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r requirements.txt
COPY backend/ /code/
RUN rm -rf scripts/templates
COPY --from=frontend /code/build/ /code/scripts/templates/
CMD ["python", "app.py"]
